# Generated by Django 6.0.2 on 2026-03-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms_engine", "0001_initial"),
        ("lawfirms", "0001_initial"),
        ("tenants", "0001_initial"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseformsubmission",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_submissions",
                to="lawfirms.case",
            ),
        ),
        migrations.AddField(
            model_name="caseformsubmission",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="workflow_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_templates",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="forms_engine.formtemplate",
            ),
        ),
        migrations.AddField(
            model_name="caseformsubmission",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="forms_engine.formtemplate",
            ),
        ),
    ]
