# Generated by Django 6.0.2 on 2026-02-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms_engine", "0001_initial"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formtemplate",
            name="workflow_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workflows.workflowstep"
            ),
        ),
    ]
