# Generated by Django 6.0.2 on 2026-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_engine", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("textarea", "Textarea"),
                ],
                max_length=50,
            ),
        ),
    ]
