# Generated by Django 6.0.2 on 2026-05-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lawfirms", "0001_initial"),
        ("tenants", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attorney",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                help_text="Managed automatically. Do not edit directly.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_at_this_step",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="workflow_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The workflow this case follows. Saving this auto-places the case on step 1.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="workflows.workflowtemplate",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="lawfirms.client",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="lawfirms.case",
            ),
        ),
        migrations.AddField(
            model_name="lawfirm",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="law_firm",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="law_firm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="lawfirms.lawfirm",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="law_firm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="lawfirms.lawfirm",
            ),
        ),
        migrations.AddField(
            model_name="attorney",
            name="law_firm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attorneys",
                to="lawfirms.lawfirm",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="case",
            unique_together={("law_firm", "code")},
        ),
    ]
