# Generated by Django 6.0.2 on 2026-03-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawfirms", "0003_alter_case_unique_together_case_case_number_and_more"),
        ("tenants", "0001_initial"),
        ("workflows", "0005_alter_workflowtransition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="case",
            name="workflow_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="workflows.workflowtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="lawfirms.case",
            ),
        ),
        migrations.AlterField(
            model_name="lawfirm",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="law_firm",
                to="tenants.tenant",
            ),
        ),
    ]
