# Generated by Django 6.0.2 on 2026-03-09 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawfirms", "0004_alter_case_code_alter_case_workflow_template_and_more"),
        ("workflows", "0007_add_missing_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_at_this_step",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lawfirms.case"
            ),
        ),
    ]
