# Generated by Django 6.0.2 on 2026-03-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawfirms", "0005_alter_case_current_step_alter_document_case"),
        ("workflows", "0012_alter_workflowtransition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                help_text="Managed automatically. Do not edit directly.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_at_this_step",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(default="OPEN", max_length=100),
        ),
        migrations.AlterField(
            model_name="case",
            name="workflow_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The workflow this case follows. Saving this auto-places the case on step 1.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="workflows.workflowtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="lawfirms.case",
            ),
        ),
    ]
