# Generated by Django 6.0.2 on 2026-02-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("tenants", "0001_initial"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="workflow_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.workflowtemplate",
            ),
        ),
    ]
