# Generated by Django 6.0.2 on 2026-05-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Explain what happens at this step.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Display order in the progress bar. Must be unique per workflow."
                    ),
                ),
                (
                    "requires_attachment",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the attorney must upload a document before advancing.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.workflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("workflow", "order")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text='What the attorney sees as a button. e.g. "Proceed to Negotiation"',
                        max_length=200,
                    ),
                ),
                (
                    "from_step",
                    models.ForeignKey(
                        help_text="The step the case is currently on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="workflows.workflowstep",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "to_step",
                    models.ForeignKey(
                        help_text="The step the case will move to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="workflows.workflowstep",
                    ),
                ),
            ],
            options={
                "ordering": ["from_step__order", "label"],
                "unique_together": {("from_step", "label")},
            },
        ),
    ]
