# Generated by Django 6.0.2 on 2026-03-07 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0004_workflowtransition"),
    ]

    operations = [
        # Step 1: Clear old model options first
        migrations.AlterModelOptions(
            name="workflowtransition",
            options={},
        ),

        # Step 2: Remove old fields that no longer exist in the model
        migrations.RemoveField(
            model_name="workflowtransition",
            name="name",
        ),
        migrations.RemoveField(
            model_name="workflowtransition",
            name="order",
        ),
        migrations.RemoveField(
            model_name="workflowtransition",
            name="requires_approval",
        ),
        migrations.RemoveField(
            model_name="workflowtransition",
            name="requires_document",
        ),
        migrations.RemoveField(
            model_name="workflowtransition",
            name="workflow",
        ),

        # Step 3: Delete the old model that no longer exists
        migrations.DeleteModel(
            name="CaseWorkflowInstance",
        ),

        # Step 4: Update the FK fields with correct related_names
        migrations.AlterField(
            model_name="workflowtransition",
            name="from_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transitions",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="to_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transitions",
                to="workflows.workflowstep",
            ),
        ),

        # Step 5: Add the new fields
        migrations.AddField(
            model_name="workflowtransition",
            name="condition_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workflowtransition",
            name="is_default",
            field=models.BooleanField(default=False),
        ),

        # Step 6: NOW set unique_together — condition_label exists at this point
        migrations.AlterUniqueTogether(
            name="workflowtransition",
            unique_together={("from_step", "condition_label")},
        ),
    ]