# Generated by Django 6.0.2 on 2026-03-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("workflows", "0008_alter_workflowtransition_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowstep",
            name="step_type",
        ),
        migrations.AlterField(
            model_name="workflowtemplate",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="condition_field",
            field=models.CharField(
                blank=True,
                help_text="Name of the context key to evaluate e.g. 'decision'. Leave blank for a default/unconditional transition.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="condition_value",
            field=models.CharField(
                blank=True,
                help_text="The value that activates this transition e.g. 'APPROVED'. Leave blank for a default/unconditional transition.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="from_step",
            field=models.ForeignKey(
                help_text="The step this transition departs FROM",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transitions",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="label",
            field=models.CharField(
                help_text="Human-readable label shown on UI buttons e.g. 'Approve', 'Reject'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower number = evaluated first. Use to break ties.",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="to_step",
            field=models.ForeignKey(
                help_text="The step this transition leads TO",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transitions",
                to="workflows.workflowstep",
            ),
        ),
    ]
