# Generated by Django 6.0.2 on 2026-03-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0009_remove_workflowstep_step_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtransition",
            name="condition_field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="condition_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="from_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transitions",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="label",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="priority",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="to_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transitions",
                to="workflows.workflowstep",
            ),
        ),
    ]
