# Generated by Django 6.0.2 on 2026-03-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0012_alter_workflowtransition_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflowtransition",
            options={"ordering": ["from_step__order", "label"]},
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="description",
            field=models.TextField(
                blank=True, help_text="Explain what happens at this step.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Display order in the progress bar. Must be unique per workflow."
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="requires_attachment",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the attorney must upload a document before advancing.",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="from_step",
            field=models.ForeignKey(
                help_text="The step the case is currently on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transitions",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="label",
            field=models.CharField(
                help_text='What the attorney sees as a button. e.g. "Proceed to Negotiation"',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="to_step",
            field=models.ForeignKey(
                help_text="The step the case will move to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transitions",
                to="workflows.workflowstep",
            ),
        ),
    ]
